# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDKSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKSample
  pod 'RW'
  pod 'SnackBar.swift'

  target 'SDKSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDKSampleUITests' do
    # Pods for testing
  end

end

target 'NotificationServiceExtension' do
  use_frameworks!
  pod 'RW'
end

target 'NotificationContentExtension' do
  use_frameworks!
  pod 'YouTubePlayer'
end
